name: Gitee repos mirror periodic job

on:
  pull_request:
    paths:
    - '.github/workflows/**'
    # Runs at every pull requests submitted in master branch 
    branches: [ master ]
  push:
  schedule:
    # Runs at 01:00 UTC (9:00 AM Beijing) every day
    - cron:  '0 1 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Mirror the Github organization repos to Gitee.
      uses: Yikun/hub-mirror-action@v0.12
      with:
        src: github/leo6033
        dst: gitee/csu-lmw
        dst_key: ${{ secrets.GITEE }}
        dst_token:  ${{ secrets.GITEE_TOKEN }}
        white_list: "General"